config-version: 1
IDK_Helper_name: "IDK Help"
IDK_Helper_lore:
  - ""
IDK_Workbench_name: "IDK Workbench"
IDK_Workbench_lore:
  - ""
menu_title: "IDK Menu"
workbench_title: "IDK Workbench"
Information_name: "Information"
Information_lore:
  - "Author: MinecraftBaymax"
  - "Add by IDK plugin."
Help:
  -  "IDK plugin help:"
  -  "\n/IDK help - This help message"
  -  "\n/IDK gm <number of gamemodes> - Change your gamemode"
  -  "\n/IDK open workbench - Open a chest or a workbench"
  -  "\n/IDK menu - open IDK menu"
  -  "\n/IDK ping - check your ping in game"
  -  "\n/IDK reload - reload config file"