name: IDK #插件名
version: '${project.version}' #插件版本
main: idk.team.IDK #插件主类
api-version: '1.13' #插件API版本
author: Baymaxawa #插件作者
website: idk.minecraftisbest.top #插件网站
loadbefore: [Luckperms]
commands: #命令
  IDK: #命令名
    description: "Main plugin command." #命令描述
    permission: IDK.command.IDK #命令所需权限
    #aliases: IDK #命令简写
    usage: "Check /idk help" #命令用法(命令输错或不存在时输出的内容，不写则会报错)
permissions:
  IDK.command.IDK:
    description: "Main plugin command permission."
    default: op
    children:
      - "IDK.command.IDK.plugin"
      - "IDK.command.IDK.reload"
      - "IDK.command.IDK.gm"
      - "IDK.command.IDK.menu"
      - "IDK.command.IDK.open"
      - "IDK.command.IDK.help"
      - "IDK.command.IDK.ping"
  IDK.command.IDK.plugin:
    description: "Main plugin management command permission."
    default: op
  IDK.command.IDK.reload:
    description: "Main plugin reload command permission."
    default: op
  IDK.command.IDK.gm:
    description: "Main plugin gm command permission."
    default: op
  IDK.command.IDK.menu:
    description: "Main plugin menu command permission."
    default: op
  IDK.command.IDK.open:
    description: "Main plugin open command permission."
    default: op
    children:
      - "IDK.command.IDK.open.workbench"
  IDK.command.IDK.open.workbench:
    description: "Main plugin open remote workbench function permission."
    default: op
  IDK.command.IDK.help:
    description: "Main plugin help command permission."
    default: op
    children:
      - "IDK.command.IDK.help.plugin"
  IDK.command.IDK.help.plugin:
    description: "Main plugin help command for plugin management command's permission."
    default: op
  IDK.command.IDK.ping:
    description: "Main plugin ping command permission."
    default: op