name: Build Pull Request

on:
  push:
    branches:
    - 1.2.x
  pull_request:
    branches:
    - 1.2.x
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Build with the Maven
        run: mvn package
      - name: Publish JUnit report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test*/TEST-*.xml'
      - name: Archive plugin jars on GitHub
        uses: actions/upload-artifact@v4
        with:
          name: IDK plugin jar
          path: target/*.jar
