name: Build Pull Request

on:
  push:
    branches:
    - master # master branch
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Build with the Maven
        run: mvn package
      - name: Archive plugin jars on GitHub
        uses: actions/upload-artifact@v4
        with:
          name: IDK plugin jars
          path: target/*.jar
