name: 发布到 Github    #你的 github.com 上的 GitHub Action 的名称
 
on: [ pull_request, workflow_dispatch ]           #何时执行你的 GitHub Action，'pull_request' -> 在每次合并（拉取）请求，'workflow_dispatch' -> 允许通过 github.com 手动执行

env:                                              #环境变量，后续可以使用 ${{ env.MINECRAFT_VERSION }} 引用，可以用作重复的信息并允许后续模组新的更新中快速更改
  VERSION: 1.2-pre3                        
  JAVA_VERSION: 17
  GITHUB_TOKEN: 114514

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查环境变量
        run: env

      - name: 签出存储库
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 设置 Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: 使 Gradle Wrapper 可执行
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: 构建
        run: ./gradlew clean build

      - name: 发布到 Github
        uses: Kir-Antipov/mc-publish@v3.3                                 #指定 MC-Publish Github Action 版本 3.2
        with:
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.VERSION}}"                             
          version: "${{env.VERSION}}"
          github-prerelease: true
          changelog-file: CHANGELOG.md                                      #指定新更新的内容的文件（路径从项目根目录开始）
